---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: projects
  label: Projects
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: directory
  path: events
  label: Events
  create: documents
  match: "**/*.md"
  templates:
  - event
- type: document
  path: data/capabilities.json
  label: Capabilities
- type: document
  path: data/logo-grid.json
  label: Logo Grid
- type: document
  path: data/about.json
  label: About
- type: document
  path: data/theme.json
  label: Home
- type: document
  path: data/footer.json
  label: Footer
- type: document
  path: data/titles.json
  label: Titles
upload_dir: ''
public_path: https://s3.amazonaws.com/forestry.iconinteractive.com
front_matter_path: " "
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - GRAPHQL_ENDPOINT=/___graphql
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
